package com.i550.qstats.Model.PlayerStats;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;


import java.util.HashMap;

import java.util.Map;

public class PlayerProfileStats {
    @SerializedName("champions")
        Map<String, Champions> champions = new HashMap<>();
    }


class Champions {
    @SerializedName("gameModes")
    Map<String, GameModes> gameModes = new HashMap<>();
    @SerializedName("damageStatusList")
    Map<String, DamageStatusList> damageStatusList = new HashMap<>();
    @SerializedName("medals")
    String medals;
}

class DamageStatusList {
    int hits;
    int shots;
    int kills;
    int headshots;
    int damage;
}

class GameModes {

    @SerializedName("won")
    @Expose
    public Integer won;
    @SerializedName("lost")
    @Expose
    public Integer lost;
    @SerializedName("tie")
    @Expose
    public Integer tie;
    @SerializedName("lifeTime")
    @Expose
    public Integer lifeTime;
    @SerializedName("timePlayed")
    @Expose
    public Integer timePlayed;
    @SerializedName("kills")
    @Expose
    public Integer kills;
    @SerializedName("deaths")
    @Expose
    public Integer deaths;
    @SerializedName("powerPickups")
    @Expose
    public Integer powerPickups;
    @SerializedName("megaHealthPickups")
    @Expose
    public Integer megaHealthPickups;
    @SerializedName("heavyArmorPickups")
    @Expose
    public Integer heavyArmorPickups;
    @SerializedName("tacticalPickups")
    @Expose
    public Integer tacticalPickups;
    @SerializedName("score")
    @Expose
    public Integer score;
    @SerializedName("captured")
    @Expose
    public Integer captured;
    @SerializedName("defended")
    @Expose
    public Integer defended;
    @SerializedName("scoringEvents")
    @Expose
    public ScoringEvents scoringEvents = new ScoringEvents();
    @SerializedName("healed")
    @Expose
    public Integer healed;
    @SerializedName("smallArmorPickups")
    @Expose
    public Integer smallArmorPickups;
    @SerializedName("rankedWon")
    @Expose
    public Integer rankedWon;
    @SerializedName("rankedLost")
    @Expose
    public Integer rankedLost;
    @SerializedName("rankedTied")
    @Expose
    public Integer rankedTied;
    @SerializedName("rankedTimePlayed")
    @Expose
    public Integer rankedTimePlayed;

   /* @Override
    public String toString() {
        return new ToStringBuilder(this).append("won", won).append("lost", lost).append("tie", tie).append("lifeTime", lifeTime).append("timePlayed", timePlayed).append("kills", kills).append("deaths", deaths).append("powerPickups", powerPickups).append("megaHealthPickups", megaHealthPickups).append("heavyArmorPickups", heavyArmorPickups).append("tacticalPickups", tacticalPickups).append("score", score).append("captured", captured).append("defended", defended).append("scoringEvents", scoringEvents).append("healed", healed).append("smallArmorPickups", smallArmorPickups).append("rankedWon", rankedWon).append("rankedLost", rankedLost).append("rankedTied", rankedTied).append("rankedTimePlayed", rankedTimePlayed).toString();
    }*/

}


class ScoringEvents {

    @SerializedName("SCORING_EVENT_KILL")
    @Expose
    public Integer sCORINGEVENTKILL;
    @SerializedName("SCORING_EVENT_ASSIST")
    @Expose
    public Integer sCORINGEVENTASSIST;
    @SerializedName("SCORING_EVENT_HEADSHOT")
    @Expose
    public Integer sCORINGEVENTHEADSHOT;
    @SerializedName("SCORING_EVENT_MIDAIRKILL")
    @Expose
    public Integer sCORINGEVENTMIDAIRKILL;
    @SerializedName("SCORING_EVENT_IMPRESSIVE")
    @Expose
    public Integer sCORINGEVENTIMPRESSIVE;
    @SerializedName("SCORING_EVENT_DIEHARD")
    @Expose
    public Integer sCORINGEVENTDIEHARD;
    @SerializedName("SCORING_EVENT_FIRSTBLOOD")
    @Expose
    public Integer SCORING_EVENT_FIRSTBLOOD;
    @SerializedName("SCORING_EVENT_ABILITYKILL")
    @Expose
    public Integer SCORING_EVENT_ABILITYKILL;
    @SerializedName("SCORING_EVENT_EXCELENT")
    @Expose
    public Integer SCORING_EVENT_EXCELENT;
    @SerializedName("SCORING_EVENT_TRIPLEKILL")
    @Expose
    public Integer sCORINGEVENTTRIPLEKILL;
    @SerializedName("SCORING_EVENT_OVERKILL")
    @Expose
    public Integer sCORINGEVENTOVERKILL;
    @SerializedName("SCORING_EVENT_EXTIRPATOR")
    @Expose
    public Integer sCORINGEVENTEXTIRPATOR;
    @SerializedName("SCORING_EVENT_CRUSHER")
    @Expose
    public Integer sCORINGEVENTCRUSHER;
    @SerializedName("SCORING_EVENT_EXTERMINATOR")
    @Expose
    public Integer sCORINGEVENTEXTERMINATOR;
    @SerializedName("SCORING_EVENT_DESTROYER")
    @Expose
    public Integer sCORINGEVENTDESTROYER;
    @SerializedName("SCORING_EVENT_REAPER")
    @Expose
    public Integer sCORINGEVENTREAPER;
    @SerializedName("SCORING_EVENT_GOD_OF_DEATH")
    @Expose
    public Integer sCORINGEVENTGODOFDEATH;
    @SerializedName("SCORING_EVENT_HITMAN")
    @Expose
    public Integer sCORINGEVENTHITMAN;
    @SerializedName("SCORING_EVENT_GAUNTLET")
    @Expose
    public Integer sCORINGEVENTGAUNTLET;
    @SerializedName("SCORING_EVENT_COMBO_KILL")
    @Expose
    public Integer sCORINGEVENTCOMBOKILL;
    @SerializedName("SCORING_EVENT_RING_OUT")
    @Expose
    public Integer sCORINGEVENTRINGOUT;
    @SerializedName("SCORING_EVENT_PERFORATION")
    @Expose
    public Integer sCORINGEVENTPERFORATION;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_1")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER1;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_2")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER2;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_3")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER3;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_4")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER4;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_5")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER5;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_6")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER6;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_7")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER7;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_8")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER8;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_9")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER9;
    @SerializedName("SCORING_EVENT_SERIAL_KILLER_10")
    @Expose
    public Integer sCORINGEVENTSERIALKILLER10;
    @SerializedName("SCORING_EVENT_LAST_SHOT")
    @Expose
    public Integer sCORINGEVENTLASTSHOT;
    @SerializedName("SCORING_EVENT_ASSISTANT")
    @Expose
    public Integer sCORINGEVENTASSISTANT;
    @SerializedName("SCORING_EVENT_STOP")
    @Expose
    public Integer sCORINGEVENTSTOP;
    @SerializedName("SCORING_EVENT_GUARDIAN")
    @Expose
    public Integer sCORINGEVENTGUARDIAN;
    @SerializedName("SCORING_EVENT_SNIPER")
    @Expose
    public Integer sCORINGEVENTSNIPER;
    @SerializedName("SCORING_EVENT_REVENGE")
    @Expose
    public Integer sCORINGEVENTREVENGE;
    @SerializedName("SCORING_EVENT_CLOWN")
    @Expose
    public Integer sCORINGEVENTCLOWN;
    @SerializedName("SCORING_EVENT_FROM_THE_GRAVE")
    @Expose
    public Integer sCORINGEVENTFROMTHEGRAVE;
    @SerializedName("SCORING_EVENT_BAD_LUCK")
    @Expose
    public Integer sCORINGEVENTBADLUCK;
    @SerializedName("SCORING_EVENT_COUNTER_ABILITY")
    @Expose
    public Integer sCORINGEVENTCOUNTERABILITY;
    @SerializedName("SCORING_EVENT_MELEE_MASTERY")
    @Expose
    public Integer sCORINGEVENTMELEEMASTERY;
    @SerializedName("SCORING_EVENT_MELEE_GOD")
    @Expose
    public Integer sCORINGEVENTMELEEGOD;
    @SerializedName("SCORING_EVENT_MACHINEGUN_MASTERY")
    @Expose
    public Integer sCORINGEVENTMACHINEGUNMASTERY;
    @SerializedName("SCORING_EVENT_MACHINEGUN_GOD")
    @Expose
    public Integer sCORINGEVENTMACHINEGUNGOD;
    @SerializedName("SCORING_EVENT_SHOTGUN_MASTERY")
    @Expose
    public Integer sCORINGEVENTSHOTGUNMASTERY;
    @SerializedName("SCORING_EVENT_SHOTGUN_GOD")
    @Expose
    public Integer sCORINGEVENTSHOTGUNGOD;
    @SerializedName("SCORING_EVENT_ROCKET_LAUNCHER_MASTERY")
    @Expose
    public Integer sCORINGEVENTROCKETLAUNCHERMASTERY;
    @SerializedName("SCORING_EVENT_ROCKET_LAUNCHER_GOD")
    @Expose
    public Integer sCORINGEVENTROCKETLAUNCHERGOD;
    @SerializedName("SCORING_EVENT_LIGHTNING_GUN_MASTERY")
    @Expose
    public Integer sCORINGEVENTLIGHTNINGGUNMASTERY;
    @SerializedName("SCORING_EVENT_LIGHTNING_GUN_GOD")
    @Expose
    public Integer sCORINGEVENTLIGHTNINGGUNGOD;
    @SerializedName("SCORING_EVENT_RAILGUN_MASTERY")
    @Expose
    public Integer sCORINGEVENTRAILGUNMASTERY;
    @SerializedName("SCORING_EVENT_RAILGUN_GOD")
    @Expose
    public Integer sCORINGEVENTRAILGUNGOD;
    @SerializedName("SCORING_EVENT_NAILGUN_MASTERY")
    @Expose
    public Integer sCORINGEVENTNAILGUNMASTERY;
    @SerializedName("SCORING_EVENT_NAILGUN_GOD")
    @Expose
    public Integer sCORINGEVENTNAILGUNGOD;
    @SerializedName("SCORING_EVENT_FIGHTER")
    @Expose
    public Integer sCORINGEVENTFIGHTER;
    @SerializedName("SCORING_EVENT_TERRORIST")
    @Expose
    public Integer sCORINGEVENTTERRORIST;
    @SerializedName("SCORING_EVENT_AVENGER")
    @Expose
    public Integer sCORINGEVENTAVENGER;
    @SerializedName("SCORING_EVENT_QUAD_KILLER")
    @Expose
    public Integer sCORINGEVENTQUADKILLER;
    @SerializedName("SCORING_EVENT_RAGE")
    @Expose
    public Integer sCORINGEVENTRAGE;
    @SerializedName("SCORING_EVENT_FLOCK")
    @Expose
    public Integer sCORINGEVENTFLOCK;
    @SerializedName("SCORING_EVENT_DAMAGE_DEALER")
    @Expose
    public Integer sCORINGEVENTDAMAGEDEALER;
    @SerializedName("SCORING_EVENT_TELEFRAG")
    @Expose
    public Integer sCORINGEVENTTELEFRAG;
    @SerializedName("SCORING_EVENT_OBELISK_CAPTURE")
    @Expose
    public Integer sCORINGEVENTOBELISKCAPTURE;
    @SerializedName("SCORING_EVENT_OBELISK_CAPTURE_ASSIST")
    @Expose
    public Integer sCORINGEVENTOBELISKCAPTUREASSIST;
    @SerializedName("SCORING_EVENT_OBELISK_DEFEND")
    @Expose
    public Integer sCORINGEVENTOBELISKDEFEND;
    @SerializedName("SCORING_EVENT_POWERUP")
    @Expose
    public Integer sCORINGEVENTPOWERUP;
    @SerializedName("SCORING_EVENT_FFA_PERFECT")
    @Expose
    public Integer sCORINGEVENTFFAPERFECT;
    @SerializedName("SCORING_EVENT_OBELISK_MASTERY")
    @Expose
    public Integer sCORINGEVENTOBELISKMASTERY;
    @SerializedName("SCORING_EVENT_OBELISK_OFFENCE")
    @Expose
    public Integer sCORINGEVENTOBELISKOFFENCE;
    @SerializedName("SCORING_EVENT_MATCH_WIN")
    @Expose
    public Integer sCORINGEVENTMATCHWIN;
    @SerializedName("SCORING_EVENT_MATCH_COMPLETE")
    @Expose
    public Integer sCORINGEVENTMATCHCOMPLETE;
    @SerializedName("SCORING_EVENT_TEAM_WIN")
    @Expose
    public Integer sCORINGEVENTTEAMWIN;
    @SerializedName("SCORING_EVENT_TEAM_TIE")
    @Expose
    public Integer sCORINGEVENTTEAMTIE;
    @SerializedName("SCORING_EVENT_1_PLACE")
    @Expose
    public Integer sCORINGEVENT1PLACE;
    @SerializedName("SCORING_EVENT_2_PLACE")
    @Expose
    public Integer sCORINGEVENT2PLACE;
    @SerializedName("SCORING_EVENT_3_PLACE")
    @Expose
    public Integer sCORINGEVENT3PLACE;
    @SerializedName("SCORING_EVENT_MVP")
    @Expose
    public Integer sCORINGEVENTMVP;
    @SerializedName("SCORING_EVENT_DAMAGE")
    @Expose
    public Integer sCORINGEVENTDAMAGE;
    @SerializedName("SCORING_EVENT_ABILITY_HEAL")
    @Expose
    public Integer sCORINGEVENTABILITYHEAL;
    @SerializedName("SCORING_EVENT_BLOCKING")
    @Expose
    public Integer sCORINGEVENTBLOCKING;
    @SerializedName("SCORING_EVENT_PICKUP_MAJOR")
    @Expose
    public Integer sCORINGEVENTPICKUPMAJOR;
    @SerializedName("SCORING_EVENT_PICKUP_WEAPON")
    @Expose
    public Integer sCORINGEVENTPICKUPWEAPON;
    @SerializedName("SCORING_EVENT_TOTEM_DESTROY")
    @Expose
    public Integer sCORINGEVENTTOTEMDESTROY;
    @SerializedName("SCORING_EVENT_ABILITY_USE_RANGER")
    @Expose
    public Integer sCORINGEVENTABILITYUSERANGER;
    @SerializedName("SCORING_EVENT_FIRST_GAME")
    @Expose
    public Integer sCORINGEVENTFIRSTGAME;
    @SerializedName("SCORING_EVENT_FIRST_WIN")
    @Expose
    public Integer sCORINGEVENTFIRSTWIN;
    @SerializedName("SCORING_EVENT_ABILITY_USE_VISOR")
    @Expose
    public Integer sCORINGEVENTABILITYUSEVISOR;
    @SerializedName("SCORING_EVENT_ABILITY_USE_SCALEBEARER")
    @Expose
    public Integer sCORINGEVENTABILITYUSESCALEBEARER;
    @SerializedName("SCORING_EVENT_ABILITY_USE_NYX")
    @Expose
    public Integer sCORINGEVENTABILITYUSENYX;
    @SerializedName("SCORING_EVENT_ABILITY_USE_GALENA")
    @Expose
    public Integer sCORINGEVENTABILITYUSEGALENA;
    @SerializedName("SCORING_EVENT_ABILITY_USE_ANARKI")
    @Expose
    public Integer sCORINGEVENTABILITYUSEANARKI;
    @SerializedName("SCORING_EVENT_ABILITY_USE_CLUTCH")
    @Expose
    public Integer sCORINGEVENTABILITYUSECLUTCH;
    @SerializedName("SCORING_EVENT_ABILITY_USE_SLASH")
    @Expose
    public Integer sCORINGEVENTABILITYUSESLASH;
    @SerializedName("SCORING_EVENT_ABILITY_USE_SORLAG")
    @Expose
    public Integer sCORINGEVENTABILITYUSESORLAG;
    @SerializedName("SCORING_EVENT_ABILITY_USE_KEEL")
    @Expose
    public Integer sCORINGEVENTABILITYUSEKEEL;
    @SerializedName("SCORING_EVENT_ABILITY_USE_STROGG")
    @Expose
    public Integer sCORINGEVENTABILITYUSESTROGG;
    @SerializedName("SCORING_EVENT_ABILITY_USE_DOOM")
    @Expose
    public Integer sCORINGEVENTABILITYUSEDOOM;
    @SerializedName("SCORING_EVENT_ABILITY_USE_BJ")
    @Expose
    public Integer sCORINGEVENTABILITYUSEBJ;
    @SerializedName("SCORING_EVENT_HELPING_HAND")
    @Expose
    public Integer sCORINGEVENTHELPINGHAND;
    @SerializedName("SCORING_EVENT_QUATERBACK")
    @Expose
    public Integer sCORINGEVENTQUATERBACK;
    @SerializedName("SCORING_EVENT_DEFENDER")
    @Expose
    public Integer sCORINGEVENTDEFENDER;
    @SerializedName("SCORING_EVENT_SURVIVOR")
    @Expose
    public Integer sCORINGEVENTSURVIVOR;
    @SerializedName("SCORING_EVENT_SCAVENGER")
    @Expose
    public Integer sCORINGEVENTSCAVENGER;
    @SerializedName("SCORING_EVENT_MOST_DAMAGE")
    @Expose
    public Integer sCORINGEVENTMOSTDAMAGE;
    @SerializedName("SCORING_EVENT_MOST_ACCURATE")
    @Expose
    public Integer sCORINGEVENTMOSTACCURATE;
    @SerializedName("SCORING_EVENT_PARTY_BREAKER")
    @Expose
    public Integer sCORINGEVENTPARTYBREAKER;
    @SerializedName("SCORING_EVENT_DENIED")
    @Expose
    public Integer sCORINGEVENTDENIED;
    @SerializedName("SCORING_EVENT_POWERUP_MASSACRE")
    @Expose
    public Integer sCORINGEVENTPOWERUPMASSACRE;
    @SerializedName("SCORING_EVENT_POINT_BLANK")
    @Expose
    public Integer sCORINGEVENTPOINTBLANK;
    @SerializedName("SCORING_EVENT_NET_MASTER")
    @Expose
    public Integer sCORINGEVENTNETMASTER;
    @SerializedName("SCORING_EVENT_TANK")
    @Expose
    public Integer sCORINGEVENTTANK;
    @SerializedName("SCORING_EVENT_SHOWSTOPPER")
    @Expose
    public Integer sCORINGEVENTSHOWSTOPPER;
    @SerializedName("SCORING_EVENT_OT")
    @Expose
    public Integer sCORINGEVENTOT;
    @SerializedName("SCORING_EVENT_COMEBACK")
    @Expose
    public Integer sCORINGEVENTCOMEBACK;
    @SerializedName("SCORING_EVENT_PRECISE")
    @Expose
    public Integer sCORINGEVENTPRECISE;
    @SerializedName("SCORING_EVENT_COLLATERAL_DAMAGE")
    @Expose
    public Integer sCORINGEVENTCOLLATERALDAMAGE;
    @SerializedName("SCORING_EVENT_DP")
    @Expose
    public Integer sCORINGEVENTDP;
    @SerializedName("SCORING_EVENT_STOPWATCH")
    @Expose
    public Integer sCORINGEVENTSTOPWATCH;
    @SerializedName("SCORING_EVENT_NEMESIS")
    @Expose
    public Integer sCORINGEVENTNEMESIS;
    @SerializedName("SCORING_EVENT_AIRBORNE")
    @Expose
    public Integer sCORINGEVENTAIRBORNE;
    @SerializedName("SCORING_EVENT_BRING_EM_DOWN")
    @Expose
    public Integer sCORINGEVENTBRINGEMDOWN;
    @SerializedName("SCORING_EVENT_DOMINATING")
    @Expose
    public Integer sCORINGEVENTDOMINATING;
    @SerializedName("SCORING_EVENT_PROVACATEUR")
    @Expose
    public Integer sCORINGEVENTPROVACATEUR;
    @SerializedName("SCORING_EVENT_KAMIKAZE")
    @Expose
    public Integer sCORINGEVENTKAMIKAZE;
    @SerializedName("SCORING_EVENT_DISINTEGRATOR")
    @Expose
    public Integer sCORINGEVENTDISINTEGRATOR;
    @SerializedName("SCORING_EVENT_SHUB_SLAYER")
    @Expose
    public Integer sCORINGEVENTSHUBSLAYER;
    @SerializedName("SCORING_EVENT_DEADLY_SLIPGATE")
    @Expose
    public Integer sCORINGEVENTDEADLYSLIPGATE;
    @SerializedName("SCORING_EVENT_SHOOTING_RANGE")
    @Expose
    public Integer sCORINGEVENTSHOOTINGRANGE;
    @SerializedName("SCORING_EVENT_CONTROLLER")
    @Expose
    public Integer sCORINGEVENTCONTROLLER;
    @SerializedName("SCORING_EVENT_SEER")
    @Expose
    public Integer sCORINGEVENTSEER;
    @SerializedName("SCORING_EVENT_STOMPER")
    @Expose
    public Integer sCORINGEVENTSTOMPER;
    @SerializedName("SCORING_EVENT_CHOOCHOO")
    @Expose
    public Integer sCORINGEVENTCHOOCHOO;
    @SerializedName("SCORING_EVENT_ROADKILL")
    @Expose
    public Integer sCORINGEVENTROADKILL;
    @SerializedName("SCORING_EVENT_EVASIVE")
    @Expose
    public Integer sCORINGEVENTEVASIVE;
    @SerializedName("SCORING_EVENT_INSIDEOUT")
    @Expose
    public Integer sCORINGEVENTINSIDEOUT;
    @SerializedName("SCORING_EVENT_FROM_THE_SHADOW")
    @Expose
    public Integer sCORINGEVENTFROMTHESHADOW;
    @SerializedName("SCORING_EVENT_HOVERTANK")
    @Expose
    public Integer sCORINGEVENTHOVERTANK;
    @SerializedName("SCORING_EVENT_REANIMATION")
    @Expose
    public Integer sCORINGEVENTREANIMATION;
    @SerializedName("SCORING_EVENT_JUNKIE")
    @Expose
    public Integer sCORINGEVENTJUNKIE;
    @SerializedName("SCORING_EVENT_PLAGUE")
    @Expose
    public Integer sCORINGEVENTPLAGUE;
    @SerializedName("SCORING_EVENT_MELTDOWN")
    @Expose
    public Integer sCORINGEVENTMELTDOWN;
    @SerializedName("SCORING_EVENT_VENOMOUS")
    @Expose
    public Integer sCORINGEVENTVENOMOUS;
    @SerializedName("SCORING_EVENT_THEROCK")
    @Expose
    public Integer sCORINGEVENTTHEROCK;
    @SerializedName("SCORING_EVENT_THEDRILL")
    @Expose
    public Integer sCORINGEVENTTHEDRILL;
    @SerializedName("SCORING_EVENT_THESHOCKER")
    @Expose
    public Integer sCORINGEVENTTHESHOCKER;
    @SerializedName("SCORING_EVENT_DAMNED")
    @Expose
    public Integer sCORINGEVENTDAMNED;
    @SerializedName("SCORING_EVENT_BLESSED")
    @Expose
    public Integer sCORINGEVENTBLESSED;
    @SerializedName("SCORING_EVENT_CURSED")
    @Expose
    public Integer sCORINGEVENTCURSED;
    @SerializedName("SCORING_EVENT_NAZI_SLAYER")
    @Expose
    public Integer sCORINGEVENTNAZISLAYER;
    @SerializedName("SCORING_EVENT_MEIN_LEBEN")
    @Expose
    public Integer sCORINGEVENTMEINLEBEN;
    @SerializedName("SCORING_EVENT_GET_PSYCHED")
    @Expose
    public Integer sCORINGEVENTGETPSYCHED;
    @SerializedName("SCORING_EVENT_SLIDER")
    @Expose
    public Integer sCORINGEVENTSLIDER;
    @SerializedName("SCORING_EVENT_SLALOM")
    @Expose
    public Integer sCORINGEVENTSLALOM;
    @SerializedName("SCORING_EVENT_BLACK_SWAN")
    @Expose
    public Integer sCORINGEVENTBLACKSWAN;
    @SerializedName("SCORING_EVENT_BERSERKER")
    @Expose
    public Integer sCORINGEVENTBERSERKER;
    @SerializedName("SCORING_EVENT_DAISY")
    @Expose
    public Integer sCORINGEVENTDAISY;
    @SerializedName("SCORING_EVENT_SLAYER")
    @Expose
    public Integer sCORINGEVENTSLAYER;
    @SerializedName("SCORING_EVENT_TRIBOLT_GOD")
    @Expose
    public Integer sCORINGEVENTTRIBOLTGOD;
    @SerializedName("SCORING_EVENT_PINEAPPLE")
    @Expose
    public Integer sCORINGEVENTPINEAPPLE;
    @SerializedName("SCORING_EVENT_NADE_SPAM")
    @Expose
    public Integer sCORINGEVENTNADESPAM;
    @SerializedName("SCORING_EVENT_MORTAR")
    @Expose
    public Integer sCORINGEVENTMORTAR;
    @SerializedName("SCORING_EVENT_BOMBARDMENT")
    @Expose
    public Integer sCORINGEVENTBOMBARDMENT;
    @SerializedName("SCORING_EVENT_PSI_RADAR")
    @Expose
    public Integer sCORINGEVENTPSIRADAR;
    @SerializedName("SCORING_EVENT_AIR_ASSAULT")
    @Expose
    public Integer sCORINGEVENTAIRASSAULT;
    @SerializedName("SPECIAL_DAMAGE_DEALER_EVENT")
    @Expose
    public Integer sPECIALDAMAGEDEALEREVENT;
    @SerializedName("SPECIAL_HEALER_EVENT")
    @Expose
    public Integer sPECIALHEALEREVENT;
    @SerializedName("SPECIAL_DAMAGE_ABSORBED_EVENT")
    @Expose
    public Integer sPECIALDAMAGEABSORBEDEVENT;
    @SerializedName("CHAMPION_MATCH_WIN")
    @Expose
    public Integer cHAMPIONMATCHWIN;
    @SerializedName("CHAMPION_MATCH_COMPLETE")
    @Expose
    public Integer cHAMPIONMATCHCOMPLETE;
    @SerializedName("ABILLITY_KILLS_GOLD")
    @Expose
    public Integer aBILLITYKILLSGOLD;
    @SerializedName("ABILLITY_KILLS_SILVER")
    @Expose
    public Integer aBILLITYKILLSSILVER;
    @SerializedName("ABILLITY_KILLS_BRONZE")
    @Expose
    public Integer aBILLITYKILLSBRONZE;
    @SerializedName("DAMAGE_DEALT_GOLD")
    @Expose
    public Integer dAMAGEDEALTGOLD;
    @SerializedName("DAMAGE_DEALT_SILVER")
    @Expose
    public Integer dAMAGEDEALTSILVER;
    @SerializedName("DAMAGE_DEALT_BRONZE")
    @Expose
    public Integer dAMAGEDEALTBRONZE;
    @SerializedName("ASSIST_GOLD")
    @Expose
    public Integer aSSISTGOLD;
    @SerializedName("ASSIST_SILVER")
    @Expose
    public Integer aSSISTSILVER;
    @SerializedName("ASSIST_BRONZE")
    @Expose
    public Integer aSSISTBRONZE;
    @SerializedName("MACHINEGUN_KILLS_GOLD")
    @Expose
    public Integer mACHINEGUNKILLSGOLD;
    @SerializedName("MACHINEGUN_KILLS_SILVER")
    @Expose
    public Integer mACHINEGUNKILLSSILVER;
    @SerializedName("MACHINEGUN_KILLS_BRONZE")
    @Expose
    public Integer mACHINEGUNKILLSBRONZE;
    @SerializedName("RAILGUN_KILLS_GOLD")
    @Expose
    public Integer rAILGUNKILLSGOLD;
    @SerializedName("RAILGUN_KILLS_SILVER")
    @Expose
    public Integer rAILGUNKILLSSILVER;
    @SerializedName("RAILGUN_KILLS_BRONZE")
    @Expose
    public Integer rAILGUNKILLSBRONZE;
    @SerializedName("ROCKET_KILLS_GOLD")
    @Expose
    public Integer rOCKETKILLSGOLD;
    @SerializedName("ROCKET_KILLS_SILVER")
    @Expose
    public Integer rOCKETKILLSSILVER;
    @SerializedName("ROCKET_KILLS_BRONZE")
    @Expose
    public Integer rOCKETKILLSBRONZE;
    @SerializedName("NAILGUN_KILLS_GOLD")
    @Expose
    public Integer nAILGUNKILLSGOLD;
    @SerializedName("NAILGUN_KILLS_SILVER")
    @Expose
    public Integer nAILGUNKILLSSILVER;
    @SerializedName("NAILGUN_KILLS_BRONZE")
    @Expose
    public Integer nAILGUNKILLSBRONZE;
    @SerializedName("TRIBOLT_KIILS_GOLD")
    @Expose
    public Integer tRIBOLTKIILSGOLD;
    @SerializedName("TRIBOLT_KIILS_SILVER")
    @Expose
    public Integer tRIBOLTKIILSSILVER;
    @SerializedName("TRIBOLT_KIILS_BRONZE")
    @Expose
    public Integer tRIBOLTKIILSBRONZE;
    @SerializedName("SHOTGUN_KILLS_GOLD")
    @Expose
    public Integer sHOTGUNKILLSGOLD;
    @SerializedName("SHOTGUN_KILLS_SILVER")
    @Expose
    public Integer sHOTGUNKILLSSILVER;
    @SerializedName("SHOTGUN_KILLS_BRONZE")
    @Expose
    public Integer sHOTGUNKILLSBRONZE;
    @SerializedName("LIGHTNING_GUN_KILLS_GOLD")
    @Expose
    public Integer lIGHTNINGGUNKILLSGOLD;
    @SerializedName("LIGHTNING_GUN_KILLS_SILVER")
    @Expose
    public Integer lIGHTNINGGUNKILLSSILVER;
    @SerializedName("LIGHTNING_GUN_KILLS_BRONZE")
    @Expose
    public Integer lIGHTNINGGUNKILLSBRONZE;
    @SerializedName("ACCURACY_GOLD")
    @Expose
    public Integer aCCURACYGOLD;
    @SerializedName("ACCURACY_SILVER")
    @Expose
    public Integer aCCURACYSILVER;
    @SerializedName("ACCURACY_BRONZE")
    @Expose
    public Integer aCCURACYBRONZE;
    @SerializedName("GAUNTLET_KILLS_GOLD")
    @Expose
    public Integer gAUNTLETKILLSGOLD;
    @SerializedName("GAUNTLET_KILLS_SILVER")
    @Expose
    public Integer gAUNTLETKILLSSILVER;
    @SerializedName("GAUNTLET_KILLS_BRONZE")
    @Expose
    public Integer gAUNTLETKILLSBRONZE;
    @SerializedName("KILLS_BASIC")
    @Expose
    public Integer kILLSBASIC;
    @SerializedName("DAMAGE_DEALT_BASIC")
    @Expose
    public Integer dAMAGEDEALTBASIC;
    @SerializedName("ASSIST_BASIC")
    @Expose
    public Integer aSSISTBASIC;
    @SerializedName("HEAL_BASIC")
    @Expose
    public Integer hEALBASIC;
    @SerializedName("ARMOR_PICKUP_BASIC")
    @Expose
    public Integer aRMORPICKUPBASIC;
    @SerializedName("MEGA_PICKUP_BASIC")
    @Expose
    public Integer mEGAPICKUPBASIC;
    @SerializedName("POWER_PICKUP_BASIC")
    @Expose
    public Integer pOWERPICKUPBASIC;
    @SerializedName("SCORING_EVENT_INFERNO")
    @Expose
    public Integer sCORINGEVENTINFERNO;
    @SerializedName("SCORING_EVENT_TRIDENT")
    @Expose
    public Integer sCORINGEVENTTRIDENT;
    @SerializedName("SCORING_EVENT_SMELTER")
    @Expose
    public Integer sCORINGEVENTSMELTER;
    @SerializedName("SCORING_EVENT_ROPE_TRICK")
    @Expose
    public Integer sCORINGEVENTROPETRICK;
    @SerializedName("SCORING_EVENT_SWINGER")
    @Expose
    public Integer sCORINGEVENTSWINGER;
    @SerializedName("SCORING_EVENT_FLOOR_IS_LAVA")
    @Expose
    public Integer sCORINGEVENTFLOORISLAVA;
    @SerializedName("SCORING_EVENT_PICKUP_MEGA_HEALTH")
    @Expose
    public Integer sCORINGEVENTPICKUPMEGAHEALTH;
    @SerializedName("SCORING_EVENT_PICKUP_HEAVY_ARMOR")
    @Expose
    public Integer sCORINGEVENTPICKUPHEAVYARMOR;
    @SerializedName("SCORING_EVENT_ABILITY_USE_ANY")
    @Expose
    public Integer sCORINGEVENTABILITYUSEANY;
    @SerializedName("SCORING_EVENT_HANDYMAN")
    @Expose
    public Integer sCORINGEVENTHANDYMAN;
    @SerializedName("SCORING_EVENT_FORTRESS")
    @Expose
    public Integer sCORINGEVENTFORTRESS;
    @SerializedName("SCORING_EVENT_WEAPONS_FACTORY")
    @Expose
    public Integer sCORINGEVENTWEAPONSFACTORY;

   /* @Override
    public String toString() {
        return new ToStringBuilder(this).append("sCORINGEVENTKILL", sCORINGEVENTKILL).append("sCORINGEVENTASSIST", sCORINGEVENTASSIST).append("sCORINGEVENTHEADSHOT", sCORINGEVENTHEADSHOT).append("sCORINGEVENTMIDAIRKILL", sCORINGEVENTMIDAIRKILL).append("sCORINGEVENTIMPRESSIVE", sCORINGEVENTIMPRESSIVE).append("sCORINGEVENTDIEHARD", sCORINGEVENTDIEHARD).append("sCORINGEVENTFIRSTBLOOD", sCORINGEVENTFIRSTBLOOD).append("sCORINGEVENTABILITYKILL", sCORINGEVENTABILITYKILL).append("sCORINGEVENTEXCELENT", sCORINGEVENTEXCELENT).append("sCORINGEVENTTRIPLEKILL", sCORINGEVENTTRIPLEKILL).append("sCORINGEVENTOVERKILL", sCORINGEVENTOVERKILL).append("sCORINGEVENTEXTIRPATOR", sCORINGEVENTEXTIRPATOR).append("sCORINGEVENTCRUSHER", sCORINGEVENTCRUSHER).append("sCORINGEVENTEXTERMINATOR", sCORINGEVENTEXTERMINATOR).append("sCORINGEVENTDESTROYER", sCORINGEVENTDESTROYER).append("sCORINGEVENTREAPER", sCORINGEVENTREAPER).append("sCORINGEVENTGODOFDEATH", sCORINGEVENTGODOFDEATH).append("sCORINGEVENTHITMAN", sCORINGEVENTHITMAN).append("sCORINGEVENTGAUNTLET", sCORINGEVENTGAUNTLET).append("sCORINGEVENTCOMBOKILL", sCORINGEVENTCOMBOKILL).append("sCORINGEVENTRINGOUT", sCORINGEVENTRINGOUT).append("sCORINGEVENTPERFORATION", sCORINGEVENTPERFORATION).append("sCORINGEVENTSERIALKILLER1", sCORINGEVENTSERIALKILLER1).append("sCORINGEVENTSERIALKILLER2", sCORINGEVENTSERIALKILLER2).append("sCORINGEVENTSERIALKILLER3", sCORINGEVENTSERIALKILLER3).append("sCORINGEVENTSERIALKILLER4", sCORINGEVENTSERIALKILLER4).append("sCORINGEVENTSERIALKILLER5", sCORINGEVENTSERIALKILLER5).append("sCORINGEVENTSERIALKILLER6", sCORINGEVENTSERIALKILLER6).append("sCORINGEVENTSERIALKILLER7", sCORINGEVENTSERIALKILLER7).append("sCORINGEVENTSERIALKILLER8", sCORINGEVENTSERIALKILLER8).append("sCORINGEVENTSERIALKILLER9", sCORINGEVENTSERIALKILLER9).append("sCORINGEVENTSERIALKILLER10", sCORINGEVENTSERIALKILLER10).append("sCORINGEVENTLASTSHOT", sCORINGEVENTLASTSHOT).append("sCORINGEVENTASSISTANT", sCORINGEVENTASSISTANT).append("sCORINGEVENTSTOP", sCORINGEVENTSTOP).append("sCORINGEVENTGUARDIAN", sCORINGEVENTGUARDIAN).append("sCORINGEVENTSNIPER", sCORINGEVENTSNIPER).append("sCORINGEVENTREVENGE", sCORINGEVENTREVENGE).append("sCORINGEVENTCLOWN", sCORINGEVENTCLOWN).append("sCORINGEVENTFROMTHEGRAVE", sCORINGEVENTFROMTHEGRAVE).append("sCORINGEVENTBADLUCK", sCORINGEVENTBADLUCK).append("sCORINGEVENTCOUNTERABILITY", sCORINGEVENTCOUNTERABILITY).append("sCORINGEVENTMELEEMASTERY", sCORINGEVENTMELEEMASTERY).append("sCORINGEVENTMELEEGOD", sCORINGEVENTMELEEGOD).append("sCORINGEVENTMACHINEGUNMASTERY", sCORINGEVENTMACHINEGUNMASTERY).append("sCORINGEVENTMACHINEGUNGOD", sCORINGEVENTMACHINEGUNGOD).append("sCORINGEVENTSHOTGUNMASTERY", sCORINGEVENTSHOTGUNMASTERY).append("sCORINGEVENTSHOTGUNGOD", sCORINGEVENTSHOTGUNGOD).append("sCORINGEVENTROCKETLAUNCHERMASTERY", sCORINGEVENTROCKETLAUNCHERMASTERY).append("sCORINGEVENTROCKETLAUNCHERGOD", sCORINGEVENTROCKETLAUNCHERGOD).append("sCORINGEVENTLIGHTNINGGUNMASTERY", sCORINGEVENTLIGHTNINGGUNMASTERY).append("sCORINGEVENTLIGHTNINGGUNGOD", sCORINGEVENTLIGHTNINGGUNGOD).append("sCORINGEVENTRAILGUNMASTERY", sCORINGEVENTRAILGUNMASTERY).append("sCORINGEVENTRAILGUNGOD", sCORINGEVENTRAILGUNGOD).append("sCORINGEVENTNAILGUNMASTERY", sCORINGEVENTNAILGUNMASTERY).append("sCORINGEVENTNAILGUNGOD", sCORINGEVENTNAILGUNGOD).append("sCORINGEVENTFIGHTER", sCORINGEVENTFIGHTER).append("sCORINGEVENTTERRORIST", sCORINGEVENTTERRORIST).append("sCORINGEVENTAVENGER", sCORINGEVENTAVENGER).append("sCORINGEVENTQUADKILLER", sCORINGEVENTQUADKILLER).append("sCORINGEVENTRAGE", sCORINGEVENTRAGE).append("sCORINGEVENTFLOCK", sCORINGEVENTFLOCK).append("sCORINGEVENTDAMAGEDEALER", sCORINGEVENTDAMAGEDEALER).append("sCORINGEVENTTELEFRAG", sCORINGEVENTTELEFRAG).append("sCORINGEVENTOBELISKCAPTURE", sCORINGEVENTOBELISKCAPTURE).append("sCORINGEVENTOBELISKCAPTUREASSIST", sCORINGEVENTOBELISKCAPTUREASSIST).append("sCORINGEVENTOBELISKDEFEND", sCORINGEVENTOBELISKDEFEND).append("sCORINGEVENTPOWERUP", sCORINGEVENTPOWERUP).append("sCORINGEVENTFFAPERFECT", sCORINGEVENTFFAPERFECT).append("sCORINGEVENTOBELISKMASTERY", sCORINGEVENTOBELISKMASTERY).append("sCORINGEVENTOBELISKOFFENCE", sCORINGEVENTOBELISKOFFENCE).append("sCORINGEVENTMATCHWIN", sCORINGEVENTMATCHWIN).append("sCORINGEVENTMATCHCOMPLETE", sCORINGEVENTMATCHCOMPLETE).append("sCORINGEVENTTEAMWIN", sCORINGEVENTTEAMWIN).append("sCORINGEVENTTEAMTIE", sCORINGEVENTTEAMTIE).append("sCORINGEVENT1PLACE", sCORINGEVENT1PLACE).append("sCORINGEVENT2PLACE", sCORINGEVENT2PLACE).append("sCORINGEVENT3PLACE", sCORINGEVENT3PLACE).append("sCORINGEVENTMVP", sCORINGEVENTMVP).append("sCORINGEVENTDAMAGE", sCORINGEVENTDAMAGE).append("sCORINGEVENTABILITYHEAL", sCORINGEVENTABILITYHEAL).append("sCORINGEVENTBLOCKING", sCORINGEVENTBLOCKING).append("sCORINGEVENTPICKUPMAJOR", sCORINGEVENTPICKUPMAJOR).append("sCORINGEVENTPICKUPWEAPON", sCORINGEVENTPICKUPWEAPON).append("sCORINGEVENTTOTEMDESTROY", sCORINGEVENTTOTEMDESTROY).append("sCORINGEVENTABILITYUSERANGER", sCORINGEVENTABILITYUSERANGER).append("sCORINGEVENTFIRSTGAME", sCORINGEVENTFIRSTGAME).append("sCORINGEVENTFIRSTWIN", sCORINGEVENTFIRSTWIN).append("sCORINGEVENTABILITYUSEVISOR", sCORINGEVENTABILITYUSEVISOR).append("sCORINGEVENTABILITYUSESCALEBEARER", sCORINGEVENTABILITYUSESCALEBEARER).append("sCORINGEVENTABILITYUSENYX", sCORINGEVENTABILITYUSENYX).append("sCORINGEVENTABILITYUSEGALENA", sCORINGEVENTABILITYUSEGALENA).append("sCORINGEVENTABILITYUSEANARKI", sCORINGEVENTABILITYUSEANARKI).append("sCORINGEVENTABILITYUSECLUTCH", sCORINGEVENTABILITYUSECLUTCH).append("sCORINGEVENTABILITYUSESLASH", sCORINGEVENTABILITYUSESLASH).append("sCORINGEVENTABILITYUSESORLAG", sCORINGEVENTABILITYUSESORLAG).append("sCORINGEVENTABILITYUSEKEEL", sCORINGEVENTABILITYUSEKEEL).append("sCORINGEVENTABILITYUSESTROGG", sCORINGEVENTABILITYUSESTROGG).append("sCORINGEVENTABILITYUSEDOOM", sCORINGEVENTABILITYUSEDOOM).append("sCORINGEVENTABILITYUSEBJ", sCORINGEVENTABILITYUSEBJ).append("sCORINGEVENTHELPINGHAND", sCORINGEVENTHELPINGHAND).append("sCORINGEVENTQUATERBACK", sCORINGEVENTQUATERBACK).append("sCORINGEVENTDEFENDER", sCORINGEVENTDEFENDER).append("sCORINGEVENTSURVIVOR", sCORINGEVENTSURVIVOR).append("sCORINGEVENTSCAVENGER", sCORINGEVENTSCAVENGER).append("sCORINGEVENTMOSTDAMAGE", sCORINGEVENTMOSTDAMAGE).append("sCORINGEVENTMOSTACCURATE", sCORINGEVENTMOSTACCURATE).append("sCORINGEVENTPARTYBREAKER", sCORINGEVENTPARTYBREAKER).append("sCORINGEVENTDENIED", sCORINGEVENTDENIED).append("sCORINGEVENTPOWERUPMASSACRE", sCORINGEVENTPOWERUPMASSACRE).append("sCORINGEVENTPOINTBLANK", sCORINGEVENTPOINTBLANK).append("sCORINGEVENTNETMASTER", sCORINGEVENTNETMASTER).append("sCORINGEVENTTANK", sCORINGEVENTTANK).append("sCORINGEVENTSHOWSTOPPER", sCORINGEVENTSHOWSTOPPER).append("sCORINGEVENTOT", sCORINGEVENTOT).append("sCORINGEVENTCOMEBACK", sCORINGEVENTCOMEBACK).append("sCORINGEVENTPRECISE", sCORINGEVENTPRECISE).append("sCORINGEVENTCOLLATERALDAMAGE", sCORINGEVENTCOLLATERALDAMAGE).append("sCORINGEVENTDP", sCORINGEVENTDP).append("sCORINGEVENTSTOPWATCH", sCORINGEVENTSTOPWATCH).append("sCORINGEVENTNEMESIS", sCORINGEVENTNEMESIS).append("sCORINGEVENTAIRBORNE", sCORINGEVENTAIRBORNE).append("sCORINGEVENTBRINGEMDOWN", sCORINGEVENTBRINGEMDOWN).append("sCORINGEVENTDOMINATING", sCORINGEVENTDOMINATING).append("sCORINGEVENTPROVACATEUR", sCORINGEVENTPROVACATEUR).append("sCORINGEVENTKAMIKAZE", sCORINGEVENTKAMIKAZE).append("sCORINGEVENTDISINTEGRATOR", sCORINGEVENTDISINTEGRATOR).append("sCORINGEVENTSHUBSLAYER", sCORINGEVENTSHUBSLAYER).append("sCORINGEVENTDEADLYSLIPGATE", sCORINGEVENTDEADLYSLIPGATE).append("sCORINGEVENTSHOOTINGRANGE", sCORINGEVENTSHOOTINGRANGE).append("sCORINGEVENTCONTROLLER", sCORINGEVENTCONTROLLER).append("sCORINGEVENTSEER", sCORINGEVENTSEER).append("sCORINGEVENTSTOMPER", sCORINGEVENTSTOMPER).append("sCORINGEVENTCHOOCHOO", sCORINGEVENTCHOOCHOO).append("sCORINGEVENTROADKILL", sCORINGEVENTROADKILL).append("sCORINGEVENTEVASIVE", sCORINGEVENTEVASIVE).append("sCORINGEVENTINSIDEOUT", sCORINGEVENTINSIDEOUT).append("sCORINGEVENTFROMTHESHADOW", sCORINGEVENTFROMTHESHADOW).append("sCORINGEVENTHOVERTANK", sCORINGEVENTHOVERTANK).append("sCORINGEVENTREANIMATION", sCORINGEVENTREANIMATION).append("sCORINGEVENTJUNKIE", sCORINGEVENTJUNKIE).append("sCORINGEVENTPLAGUE", sCORINGEVENTPLAGUE).append("sCORINGEVENTMELTDOWN", sCORINGEVENTMELTDOWN).append("sCORINGEVENTVENOMOUS", sCORINGEVENTVENOMOUS).append("sCORINGEVENTTHEROCK", sCORINGEVENTTHEROCK).append("sCORINGEVENTTHEDRILL", sCORINGEVENTTHEDRILL).append("sCORINGEVENTTHESHOCKER", sCORINGEVENTTHESHOCKER).append("sCORINGEVENTDAMNED", sCORINGEVENTDAMNED).append("sCORINGEVENTBLESSED", sCORINGEVENTBLESSED).append("sCORINGEVENTCURSED", sCORINGEVENTCURSED).append("sCORINGEVENTNAZISLAYER", sCORINGEVENTNAZISLAYER).append("sCORINGEVENTMEINLEBEN", sCORINGEVENTMEINLEBEN).append("sCORINGEVENTGETPSYCHED", sCORINGEVENTGETPSYCHED).append("sCORINGEVENTSLIDER", sCORINGEVENTSLIDER).append("sCORINGEVENTSLALOM", sCORINGEVENTSLALOM).append("sCORINGEVENTBLACKSWAN", sCORINGEVENTBLACKSWAN).append("sCORINGEVENTBERSERKER", sCORINGEVENTBERSERKER).append("sCORINGEVENTDAISY", sCORINGEVENTDAISY).append("sCORINGEVENTSLAYER", sCORINGEVENTSLAYER).append("sCORINGEVENTTRIBOLTGOD", sCORINGEVENTTRIBOLTGOD).append("sCORINGEVENTPINEAPPLE", sCORINGEVENTPINEAPPLE).append("sCORINGEVENTNADESPAM", sCORINGEVENTNADESPAM).append("sCORINGEVENTMORTAR", sCORINGEVENTMORTAR).append("sCORINGEVENTBOMBARDMENT", sCORINGEVENTBOMBARDMENT).append("sCORINGEVENTPSIRADAR", sCORINGEVENTPSIRADAR).append("sCORINGEVENTAIRASSAULT", sCORINGEVENTAIRASSAULT).append("sPECIALDAMAGEDEALEREVENT", sPECIALDAMAGEDEALEREVENT).append("sPECIALHEALEREVENT", sPECIALHEALEREVENT).append("sPECIALDAMAGEABSORBEDEVENT", sPECIALDAMAGEABSORBEDEVENT).append("cHAMPIONMATCHWIN", cHAMPIONMATCHWIN).append("cHAMPIONMATCHCOMPLETE", cHAMPIONMATCHCOMPLETE).append("aBILLITYKILLSGOLD", aBILLITYKILLSGOLD).append("aBILLITYKILLSSILVER", aBILLITYKILLSSILVER).append("aBILLITYKILLSBRONZE", aBILLITYKILLSBRONZE).append("dAMAGEDEALTGOLD", dAMAGEDEALTGOLD).append("dAMAGEDEALTSILVER", dAMAGEDEALTSILVER).append("dAMAGEDEALTBRONZE", dAMAGEDEALTBRONZE).append("aSSISTGOLD", aSSISTGOLD).append("aSSISTSILVER", aSSISTSILVER).append("aSSISTBRONZE", aSSISTBRONZE).append("mACHINEGUNKILLSGOLD", mACHINEGUNKILLSGOLD).append("mACHINEGUNKILLSSILVER", mACHINEGUNKILLSSILVER).append("mACHINEGUNKILLSBRONZE", mACHINEGUNKILLSBRONZE).append("rAILGUNKILLSGOLD", rAILGUNKILLSGOLD).append("rAILGUNKILLSSILVER", rAILGUNKILLSSILVER).append("rAILGUNKILLSBRONZE", rAILGUNKILLSBRONZE).append("rOCKETKILLSGOLD", rOCKETKILLSGOLD).append("rOCKETKILLSSILVER", rOCKETKILLSSILVER).append("rOCKETKILLSBRONZE", rOCKETKILLSBRONZE).append("nAILGUNKILLSGOLD", nAILGUNKILLSGOLD).append("nAILGUNKILLSSILVER", nAILGUNKILLSSILVER).append("nAILGUNKILLSBRONZE", nAILGUNKILLSBRONZE).append("tRIBOLTKIILSGOLD", tRIBOLTKIILSGOLD).append("tRIBOLTKIILSSILVER", tRIBOLTKIILSSILVER).append("tRIBOLTKIILSBRONZE", tRIBOLTKIILSBRONZE).append("sHOTGUNKILLSGOLD", sHOTGUNKILLSGOLD).append("sHOTGUNKILLSSILVER", sHOTGUNKILLSSILVER).append("sHOTGUNKILLSBRONZE", sHOTGUNKILLSBRONZE).append("lIGHTNINGGUNKILLSGOLD", lIGHTNINGGUNKILLSGOLD).append("lIGHTNINGGUNKILLSSILVER", lIGHTNINGGUNKILLSSILVER).append("lIGHTNINGGUNKILLSBRONZE", lIGHTNINGGUNKILLSBRONZE).append("aCCURACYGOLD", aCCURACYGOLD).append("aCCURACYSILVER", aCCURACYSILVER).append("aCCURACYBRONZE", aCCURACYBRONZE).append("gAUNTLETKILLSGOLD", gAUNTLETKILLSGOLD).append("gAUNTLETKILLSSILVER", gAUNTLETKILLSSILVER).append("gAUNTLETKILLSBRONZE", gAUNTLETKILLSBRONZE).append("kILLSBASIC", kILLSBASIC).append("dAMAGEDEALTBASIC", dAMAGEDEALTBASIC).append("aSSISTBASIC", aSSISTBASIC).append("hEALBASIC", hEALBASIC).append("aRMORPICKUPBASIC", aRMORPICKUPBASIC).append("mEGAPICKUPBASIC", mEGAPICKUPBASIC).append("pOWERPICKUPBASIC", pOWERPICKUPBASIC).append("sCORINGEVENTINFERNO", sCORINGEVENTINFERNO).append("sCORINGEVENTTRIDENT", sCORINGEVENTTRIDENT).append("sCORINGEVENTSMELTER", sCORINGEVENTSMELTER).append("sCORINGEVENTROPETRICK", sCORINGEVENTROPETRICK).append("sCORINGEVENTSWINGER", sCORINGEVENTSWINGER).append("sCORINGEVENTFLOORISLAVA", sCORINGEVENTFLOORISLAVA).append("sCORINGEVENTPICKUPMEGAHEALTH", sCORINGEVENTPICKUPMEGAHEALTH).append("sCORINGEVENTPICKUPHEAVYARMOR", sCORINGEVENTPICKUPHEAVYARMOR).append("sCORINGEVENTABILITYUSEANY", sCORINGEVENTABILITYUSEANY).append("sCORINGEVENTHANDYMAN", sCORINGEVENTHANDYMAN).append("sCORINGEVENTFORTRESS", sCORINGEVENTFORTRESS).append("sCORINGEVENTWEAPONSFACTORY", sCORINGEVENTWEAPONSFACTORY).toString();
    }*/

}


